language: java

notifications:
  email:
    recipients:
      - dataflow-sdk+travis@google.com
    on_success: change
    on_failure: always

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install:
  - mvn install clean -U -DskipTests=true

script:
  - mvn verify -U
