language: java

os:
  - linux
  - osx

notifications:
  email:
    recipients:
      - dataflow-sdk+travis@google.com
    on_success: change
    on_failure: always

install:
  - mvn install clean -U -DskipTests=true

script:
  - mvn verify -U
  - ./test_wordcount.sh
